version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /home/davi/mongodb/database:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: false
  api:
    image: api/consent
    restart: always
    build: .
    working_dir: /var/www/consent
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - mongodb